# docker-compose.yml
version: "3.8"
services:
   express-app:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - .:/app
     ports:
       - 3000:3000
     command: npm run start
